name: DockerHub ERC-712 Build 

on:
  push:
    branches:
      - erc-712

env:
  DOCKER_REPO: openlaw/snapshot-hub
  IMAGE_NAME: openlaw/snapshot-hub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check available environment variables
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x
      
      - name: Build docker image and tag
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ secrets.PUB_REPO_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PUB_REPO_DOCKERHUB_ACCESS_TOKEN }}
          repository: ${{ env.DOCKER_REPO }}
          # Automatically tags the built image with the git short SHA prefixed with the branch name, e.g: master-xxxxxxx, erc-712
          tags: ${{ env.GITHUB_REF_SLUG }}-${{ env.GITHUB_SHA_SHORT }}, erc-712
          # Only push on git erc-712 branch
          push: ${{ startsWith(github.ref, 'refs/heads/erc-712') }}
